### ISSUE TITLE
New endpoints, current ones expiring March 31

### ISSUE THREAD

**Issue by jmalko** [phpfui/ConstantContact#1]
Hey there!  I am not familiar with the automated `update.php` solution in order to make a PR.  Was given a heads up from CC a day or two ago about new API endpoints for all new developer 'apps'.  And that current developer apps will expire on March 31, 2022.
```
This application sends GET requests to https://authz.constantcontact.com/oauth2/default/v1/authorize to initiate authorization requests.

This application sends POST requests to https://authz.constantcontact.com/oauth2/default/v1/token to exchange authorization codes for bearer tokens.
```

**Comment by phpfui** [comment]
OK, looks like this explains it (https://v3.developer.constantcontact.com/api_guide/auth_update_apps.html).

I will take a look, fix my application (if needed), and make appropriate changes to the library as needed.  Since the PHP interface should not change, it should just work for when composer updates the project.

Thanks for the heads up.  I can't believe they are changing this.  I started this project in August of 2021, and there was no depreciation notice then.  Seems like this is a change that should be depreciated a year out!

**Comment by jmalko** [comment]
I had just finished implementation on a project with your lib, so yeah, my heart dropped when I realized this was happening (I was ready to move on to other parts of the project!).  Agreed, March 31 is unbelievable.

**Comment by jmalko** [comment]
Icing on the cake is that all new keys need the new URL, while existing ones need to use the deprecated one.

**Comment by phpfui** [comment]
Looks like they were having some attacks on the API.  There are (at least) two new parameters that need to be passed. (https://v3.developer.constantcontact.com/api_guide/pkce_flow.html)  Apparently PKCE OAUTH is more secure.

**Comment by phpfui** [comment]
So looks like are no modern OAuth PKCE client packages out there. I found one, but not usable. Will update and publish one.  Also I always wanted to do a typed object for settings, so will do a library for that as well, building off the Definitions base class that is in the library already.

May take a week or so to get it all tested and ready to go, but should have something by the end of Feb.

What a nightmare!

**Comment by jmalko** [comment]
What a difficult API to work with.  I'm thankful for your effort here!

**Comment by phpfui** [comment]
The problem is really just the OAuth2 stuff. There is a good package for it, but it does not support PKCE yet (although there is a PR for it).

But once I figured out what a swagger file was, it is very easy to support.

**Comment by phpfui** [comment]
So this is fixed.  I have tested it on my site and it seems to work.  You might have to generate a new secret.  I have not issued a release (figuring I would wait till tomorrow to get a 22.3 version), but you should be able to install dev-master to test.

Let me know if it works, and I can do a new version.

Thanks!

PS. Problem is a bug in CC API.  They do not accept a correctly encoded URL with the plus sign in it (%2B), you need to pass the actual + sign.

**Comment by jmalko** [comment]
Lovely.  Thank you so much, I will put this through testing tomorrow!

**Comment by jmalko** [comment]
Is $_SESSION necessary here?

https://flareapp.io/share/NPL9ZW87#F70

**Comment by jmalko** [comment]
I see that it is a critical part of the program.  Added `session_start();` to the top of `src/ConstantContact/Client.php` and now it works.  Doesn't seem to help if I throw that into my code however.  Would it be a good thing to add into this library or to make users responsible for figuring out session initialization?

**Comment by jmalko** [comment]
#2

**Comment by phpfui** [comment]
So I looked around, and all session management stuff is highly framework oriented (as it probably should be).  So I just documented in the readme that you need to enable sessions to support the new authentication.  Technically I could just fake the authentication of the state parameter (not test it), but that is not good form.

I want to keep this package independent of any framework so it is more widely usable. So you should probably require the same thing of your users, sessions have to be turned on in order for the program to work.  Thinking now I will do callback storage, but default it to use sessions.  That will solve the problem more generically.

**Comment by jmalko** [comment]
Sounds good to me.  For today I will roll with enabling php sessions from my addon.  Found a place in there where it works.

**Comment by phpfui** [comment]
Yeah, I am thinking it will take a few more days to come up with the best solution. But it will be backward compatible with what you did, assuming you init the session someplace else.

Thanks for letting me know about this. I would probably be blindsided by it April 1 as I am not the contact person on the CC account, so I had no clue!
