### ISSUE TITLE
Contact Delete returns false?

### ISSUE THREAD

**Issue by degive** [phpfui/ConstantContact#11]
So the Contact delete works great now but why is it that it returns false on success, shouldn't it return true?

**Comment by phpfui** [comment]
Could be a brain fart. Will check logic Monday.  Thanks for confirming.

**Comment by degive** [comment]
I get lots if those ;-)

**Comment by phpfui** [comment]
Turns out Constant Contact returns various 200 status codes for a successful delete. I was only checking for one.  Grab the latest version.  Should work now.
