### ISSUE TITLE
How to use setSessionCallback?

### ISSUE THREAD

**Issue by pixelone** [phpfui/ConstantContact#13]
Thanks for this library, your time is greatly appreciated!  

Any example on how to use the setSessionCallback?  I was testing this with Laravel real quick, but I am unable to get $client->accessToken or $client->refreshToken to output.  If I switch to using PHP's start_session() it works, but the application I want to implement into uses its own session handler. 

I assume I am doing the callback incorrect or missing something?  

    $client = new Client($apiKey, $secret, $redirectURI);

    $client->setSessionCallback(function ($key, $value) use ($request) {
        $request->session()->put($key, $value);
        return $request->session()->get($key) ?? '';
    });

    $client->acquireAccessToken($_GET);

    echo $client->accessToken . '<br>';
    echo $client->refreshToken . '<br>';

    dd($request->session()->all());`

**Comment by phpfui** [comment]
Looks like you are not following the contact the callback expects. See
http://phpfui.com/?n=PHPFUI%5CConstantContact&c=Client

Basically you need to delete the session variable if passed in a null
value, otherwise store it.

Let me know if that doesn't work.

**Comment by phpfui** [comment]
Yes, your new implementation looks correct now.

And yes, it should update the refresh token after the call.
