### ISSUE TITLE
Session handler and samesite cookies. 

### ISSUE THREAD

**Issue by pixelone** [phpfui/ConstantContact#14]
Hello, 

Appreciate your hard work on this library.   

Do you have any suggestion on how this can be used with Samesite cookies set as Strict?  

I found that in our Session implementation with Laravel, when cookies are stored as LAX it will Authorize fine, however when Samesite Cookies are set as Strict, I get an Unauthorized response back.  I assume because of the offsite transfer the session is lost.

Is there any other suggestion on how to still use this Library with Samesite cookies set as strict or an alternative way of handling this from within the session handler? 

Again, your work and time on this is greatly appreciated, hoping some simple way around this.

**Comment by phpfui** [comment]
I don't seem to have a problem on my sites, but not using Laravel.  This is how I set cookies:

```php
	public function set(string $name, string $value = '', bool $permanent = false) : static
		{
		$permanent ? \time() + 32_000_000 : 0; // expires in about a year if permanent
		$options = [
			'expires' => $permanent ? \time() + 32_000_000 : 0, // expires in about a year if permanent
			'path' => '/',
			'domain' => $_SERVER['SERVER_NAME'],
			'secure' => true,
			'httponly' => true,
			'samesite' => 'Strict',
		];
		\setcookie($this->prefix . $name, $value, $options);

		return $this;
		}
```

You might want to check the Constant Contact API docs to see what they say about cookies. Let me know what you figure out.

**Comment by phpfui** [comment]
I would suspect a Laravel issue. I do the initial authorization in the
normal UI, but the real work is done as a cron job.
