### ISSUE TITLE
Get all contacts that have pagination

### ISSUE THREAD

**Issue by handoyo** [phpfui/ConstantContact#15]
Hi,

first of all thanks a lot for the library.

I'm trying to get all contacts by using this code. I have 3 contacts for testing purpose.
`$contactsResponse = $contactsEndPoint->get('all',null,$list_id,null,null,null,null,null,null,null,null,null,null,true,1);
      
        do {
            $contactsResponse = $contactsEndPoint->next();
            print_r(contactsResponse);
        } while ($contactsResponse);`

I'm getting 504 document error and i'm only get the first and the second contact but no on the third contact.

What is the correct way to use the next()?

Thanks a lot.

**Comment by phpfui** [comment]
I believe you get an array from the get request that is paginated.  So if you have more than one page, you would need to call next().  But in your case, you just have 3 things, so not paginated.

So try printing the $contactsResponse before calling next.  That should contain an array that you can foreach through to get what you want.

Let me know if that does not work.

**Comment by handoyo** [comment]
In the get i set the limit to 1, hoping to get the other 2.

if i set the limit to 500, i get all of the contacts without issue and there are no next.

**Comment by phpfui** [comment]
This is the logic I am using for getting all contacts.  I wrote all this a while ago, so not sure how everything works!

```php
// Get all current Constant Contact users
$contactsClient = new \PHPFUI\ConstantContact\V3\Contacts($client);
$list = $contactsClient->get(status: 'all', limit: 500);
do
	{
	foreach ($list['contacts'] as $contact)
		{
		print_r($contact);
		}
	$list = $contactsClient->next();
	}
while ($list);
```

You seem to have a lot of parameters on the get() call.  Maybe use named parameters?  You could easily be off by one.

**Comment by handoyo** [comment]
Thanks a lot for the example, i will give it a test.

Do you have examples for adding contacts, subscribe, unsubscribe and re-subscibe as well?

**Comment by phpfui** [comment]
Actually I do have some examples!  Check out my Bicycle Club Website repo: https://github.com/phpfui/BicycleClubWebsite2023

Looks like the good stuff is here: https://github.com/phpfui/BicycleClubWebsite2023/blob/master/App/Cron/Job/ConstantContactSync.php

Let me know if you get it working.

**Comment by handoyo** [comment]
Thanks, I will look into it and let you know the results.

**Comment by handoyo** [comment]
> This is the logic I am using for getting all contacts. I wrote all this a while ago, so not sure how everything works!
> 
> ```
> // Get all current Constant Contact users
> $contactsClient = new \PHPFUI\ConstantContact\V3\Contacts($client);
> $list = $contactsClient->get(status: 'all', limit: 500);
> do
> 	{
> 	foreach ($list['contacts'] as $contact)
> 		{
> 		print_r($contact);
> 		}
> 	$list = $contactsClient->next();
> 	}
> while ($list);
> ```
> 
> You seem to have a lot of parameters on the get() call. Maybe use named parameters? You could easily be off by one.

i have tested using this code and set the limit to 1. i only get 1 contact and it's keep looping and then i get 504 Gateway error..

What could possible goes wrong?

Thanks.

**Comment by phpfui** [comment]
Not sure at this point. You will probably need to talk to CC support to see if they have any idea of what is happening.

If you look into the client class code, I think you should be able to see the actual URLs and data sent to CC. They don't support any libraries just to make things super difficult.

**Comment by handoyo** [comment]
I give another test by calling the `$contactsClient->next();` twice and i get all of the other 2 contacts.

so i use this approach:

`$contactsResponse = $contactsEndPoint->get(status: 'all',include_count: true,lists: $list_id, limit: 1);
        $counts = $contactsResponse['contacts_count'];
        
        $pages =  1;
        if ($counts > 1) {
            $pages = intdiv($counts,1);
        }

        if ($pages > 1) {
            for ($i = 2; $i <= $pages; $i++) {
                print_r($contactsEndPoint->next());
            }
        }`

It is working for me. maybe you have a better way?

**Comment by phpfui** [comment]
Looks like it would work. I would use a bigger limit and iterate through the returned array of contacts.  That would minimize the number of API calls you are making. I believe CC has a rate limited API, so you can't call them too often.  I think I added a rate limiter into the client, so it should not be a problem. Still not sure why you are getting a gateway error.

**Comment by handoyo** [comment]
I have update my code to use 500 as the limit.

Another thing, i copied your code on create contact like this:

            $contactBody = new \PHPFUI\ConstantContact\Definition\ContactPostRequest();
            $contactBody->first_name = $data['firstname'];
            $contactBody->last_name = $data['lastname'];
            $contactBody->create_source = 'Account';
            $contactBody->list_memberships = [new \PHPFUI\ConstantContact\UUID($list_id)];
            $email = new \PHPFUI\ConstantContact\Definition\EmailAddressPost();
            $email->address = $data['email'];
            $email->permission_to_send = 'explicit';
            $contactBody->email_address = $data['email'];
            $contactsEndPoint->post($contactBody);

I get this error:

     Unknown Error: AbanteCart core v.1.3.4 PHPFUI\ConstantContact\Definition\Base::__construct(): Argument #1 ($initialValues) must be of type array, string given, called in /home/php81abdev7/public_html/ctct/extensions/constantcontact_integration/core/lib/ctct/vendor/phpfui/constantcontact/src/ConstantContact/Definition/Base.php on line 177 in <b>/home/php81abdev7/public_html/ctct/extensions/constantcontact_integration/core/lib/ctct/vendor/phpfui/constantcontact/src/ConstantContact/Definition/Base.php</b> on line <b>57</b>

Did i miss anything?

**Comment by phpfui** [comment]
There is now a new version that fixes the assignment of the wrong type to properties that should be an object.

Closing this as answered.  Open a new issue if you find another issue.
