### ISSUE TITLE
http_build_param Issue

### ISSUE THREAD

**Issue by iamseventhpro** [phpfui/ConstantContact#16]
When tryin to authenticate, the authentication url uses `&amp; `instead of just &.
Tried both approach and the url with just "&" is the one working.. `&amp;` returns 400 error.

After some tests, seems that it only happens when using the php head redirect (\header('location: ' . $client->getAuthorizationURL());)

Im not sure if this is related to that but when getting the access_toke, I don't get results. I have the code and state in url but still no access_token or refresh token after calling  **`$client->acquireAccessToken($_GET);`**
`
object(PHPFUI\ConstantContact\Client)#22 (17) { ["accessToken"]=> string(0) "" ["refreshToken"]=> string(0) "" ["authorizeURL":"PHPFUI\ConstantContact\Client":private]=> string(61) "https://authz.constantcontact.com/oauth2/default/v1/authorize" `

**Comment by phpfui** [comment]
Looks like an HTLM entity encode problem. Do you have source code that will reproduce the problem.

I can fix today if it is a bug in the library.

**Comment by phpfui** [comment]
Looking at the code, I don't see any HTML Entity encoding.  Try printing out the return from authorizeURL() and see if it is correct.  You may be encoding it somewhere else accidentally.

**Comment by iamseventhpro** [comment]
It seems that we have & - &amp; conversion in our settings. Disabled that. Working fine now.

**Comment by phpfui** [comment]
Thanks for the followup.  Let me know of any other problems.
