### ISSUE TITLE
allow passing Guzzle factory to Client constructor

### ISSUE THREAD

**Issue by xpavp03** [phpfui/ConstantContact#24]
Hi Bruce,
I use https://github.com/contributte/guzzlette in my project to see requests made with Guzzle. I can't see those made with your library because you create a new instance [yourself](https://github.com/phpfui/ConstantContact/blob/87dd954b6d2a68fc4e9f9d76511ef659840bce8b/src/ConstantContact/Client.php#L127). 

I think it would cause no side effects to allow passing an optional a Guzzle factory that would accept `$config`. I would use it to pass a callback to Guzzlette [ClientFactory method](https://github.com/contributte/guzzlette/blob/9c6dc89e0ca2cfdf19c5b6616e8ed97cb00f5ea9/src/ClientFactory.php#L26).

I imagine something like:
```php
$client = new PHPFUI\ConstantContact\Client(
      $clientId,
      $clientSecret,
      $receiverUrl,
      $this->guzzletteClientFactory->createClient(...)
    );
```
Then in your Client you could do:
```php
public function delete(string $url) : ?array
{
...
  $response = $this->createGuzzleClient()->request('DELETE', $url);
...
}

private function createGuzzleClient(): \GuzzleHttp\Client
{
   $config = ['headers' => $this->getHeaders(), 'handler' => $this->guzzleHandler, ];

   if ($this->guzzleFactory) {
     return $this->guzzleFactory($config);
   }

   return new \GuzzleHttp\Client($config);
}
```

What do you think?

**Comment by phpfui** [comment]
Yes, but actually no need to over complicate it.  Just pass an optional Guzzle client in.  There may be a reason I did not do that originally, but will look into it.

I would say just pass in a PSR client interface, but the API needs a rate limiter and I don't think there is an interface for that.

I can do something next week.

**Comment by xpavp03** [comment]
Passing an instance of Guzzle client to the constructor of your Client wouldn't be lazy. And passing the client to each API method (e.g. delete() would be, imho, not very pretty :)

Or maybe I misunderstood.

Passing the factory that accepts $config would allow you to register whatever you need, e.g. the rate limiter.

If you look into the code of Guzzlette createClient() - linked in my original post, you'll see that they respect $config['handler'] and use it to add their own layer.

**Comment by phpfui** [comment]
You would only need to pass the client to the client constructor. You should have one client really.

**Comment by xpavp03** [comment]
Yeah... you're right. I don't need to create an instance of your client in advance just for DI (and perhaps never use it) so there's no question of it being lazy or not.

Apologizes for my confusion.

**Comment by xpavp03** [comment]
Before you say yes, there's maybe one related thing:
\PHPFUI\ConstantContact\Client::acquireAccessToken() uses curl, not Guzzle. So if the purpose of this ticket is to allow logging then replacing curl with Guzzle seems its logical extension.

(It's not just logging, I imagine some servers may be behind proxy or require custom Guzzle settings for other reasons. But yeah, YAGNI.)

**Comment by xpavp03** [comment]
I didn't realize that `getConfig()` is deprecated. Although, [as the author says](https://github.com/guzzle/guzzle/issues/3114#issuecomment-1627228395), he doesn't plan on actually removing it. The [commit in 8.0 branch](https://github.com/guzzle/guzzle/commit/31ec0ffd0c8f65e146463752b0e1c2fc66da3d26) postpones the removal to 9.0.

Reading some tickets related to it, they mind exposing the internal structure of config but they don't all agree that it's a bad thing to allow extending the config. So chances are, if they ever remove `getConfig()` they will replace it with `getHandler()` and `getHeaders()`.

So yes, either use the factory, or use getConfig() because its removal is in such a distant future that we can plan a better response when the time comes.

To wrap up for other readers:
This library defines its own header, handler and body when constructing a new `GuzzleHttp\Client`. It could pass body to `$guzzle->request()` using the `$options` param but header and handler needs to be augmented, not overridden.

**Comment by phpfui** [comment]
I think the thing to do is work with your suggested library.  Hopefully they will work with the Guzzle people and keep their interface the same.  I have dealt with one of the Guzzle maintainers on a different project and seen him around, so I don't really want to interact with them if possible, good coder, not a people person sometimes. YMMV.

Probably get to this by end of week.

**Comment by phpfui** [comment]
I added the Guzzle Factory stuff.  You need to call setGuzzleFactory(callable).  I modeled off of [graham-campbell/guzzle-factory](https://packagist.org/packages/graham-campbell/guzzle-factory) He is one of the Guzzle maintainers, so he will probably keep his library compatible.

I will probably leave the CURL stuff as it.  It was hard enough to get OAuth2 working at all!

**Comment by phpfui** [comment]
I made the factory interface static, but now thinking it does not have to
be.

**Comment by phpfui** [comment]
New release published!
