### ISSUE TITLE
Nested objects are not recognized in \PHPFUI\ConstantContact\Definition\Base::__set()

### ISSUE THREAD

**Issue by xpavp03** [phpfui/ConstantContact#25]
Hi Bruce, I think I found a bug.

When a `getTyped()` response contains a value that should be an instance of some other object, it is incorrectly assigned as the original array, `Base::set()` doesn't attempt to create an object from the array.

The conversion does happen when the value is an array of objects.

E.g. `$contactClient->getTyped(email: $email)` correctly returns `Definition\Contacts` with an array of `Definition\ContactResource` in "property" `contacts`. However, the individual contacts then do not contain `UUID` in `contact_id` (they contain the original string) and do not contain `Definition\EmailAddress` in `email_address` (they contain the original associative array).

I checked the source code of `Base::set()` and it's not that it would incorrectly evaluate something - it just doesn't contain a code that would detect such situations. It only recognizes an array of objects.

There also may be a bug in the [constructor](https://github.com/phpfui/ConstantContact/blob/87dd954b6d2a68fc4e9f9d76511ef659840bce8b/src/ConstantContact/Definition/Base.php#L79) that sets `$this->constructingFromArray = true;` basically always because the fields always have a definition ("string", "\PHPFUI\ConstantContact\UUID"...). For that reason, [this condition](https://github.com/phpfui/ConstantContact/blob/87dd954b6d2a68fc4e9f9d76511ef659840bce8b/src/ConstantContact/Definition/Base.php#L182) never fires.

Original JSON:
```json
{
  "contacts" : [ {
    "contact_id" : "d5e4dc88-9dbf-11ef-9af2-fa163e4d7501",
    "email_address" : {
      "address" : "xxxx@mailinator.com",
      "permission_to_send" : "explicit",
      "created_at" : "2024-11-08T10:54:32Z",
      "updated_at" : "2024-11-08T10:54:32Z",
      "opt_in_source" : "Contact",
      "opt_in_date" : "2024-11-08T10:54:32Z",
      "confirm_status" : "off"
    },
    "first_name" : "Petr",
    "last_name" : "Pavel",
    "create_source" : "Contact",
    "created_at" : "2024-11-08T10:54:32Z",
    "updated_at" : "2024-11-08T10:54:32Z"
  } ]
}
```

is converted to arrays
```php
array (
  'contacts' => 
  array (
    0 => 
    array (
      'contact_id' => 'd5e4dc88-9dbf-11ef-9af2-fa163e4d7501',
      'email_address' => 
      array (
        'address' => 'xxxx@mailinator.com',
        'permission_to_send' => 'explicit',
        'created_at' => '2024-11-08T10:54:32Z',
        'updated_at' => '2024-11-08T10:54:32Z',
        'opt_in_source' => 'Contact',
        'opt_in_date' => '2024-11-08T10:54:32Z',
        'confirm_status' => 'off',
      ),
      'first_name' => 'Petr',
      'last_name' => 'Pavel',
      'create_source' => 'Contact',
      'created_at' => '2024-11-08T10:54:32Z',
      'updated_at' => '2024-11-08T10:54:32Z',
    ),
  ),
)
```

but then later in \PHPFUI\ConstantContact\Definition\Base::__set() only arrays of arrays are converted to entities, not e.g. UUID or EmailAddress:

```php
PHPFUI\ConstantContact\Definition\Contacts::__set_state(array(
   'constructingFromArray' => false,
   'data' => 
  array (
    'contacts' => 
    array (
      0 => 
      PHPFUI\ConstantContact\Definition\ContactResource::__set_state(array(
         'constructingFromArray' => false,
         'data' => 
        array (
          'contact_id' => 'd5e4dc88-9dbf-11ef-9af2-fa163e4d7501',
          'email_address' => 
          array (
            'address' => 'xxxx@mailinator.com',
            'permission_to_send' => 'explicit',
            'created_at' => '2024-11-08T10:54:32Z',
            'updated_at' => '2024-11-08T10:54:32Z',
            'opt_in_source' => 'Contact',
            'opt_in_date' => '2024-11-08T10:54:32Z',
            'confirm_status' => 'off',
          ),
          'first_name' => 'Petr',
          'last_name' => 'Pavel',
          'create_source' => 'Contact',
          'created_at' => '2024-11-08T10:54:32Z',
          'updated_at' => '2024-11-08T10:54:32Z',
        ),
         'setFields' => 
        array (
          'contact_id' => true,
          'email_address' => true,
          'first_name' => true,
          'last_name' => true,
          'create_source' => true,
          'created_at' => true,
          'updated_at' => true,
        ),
      )),
    ),
  ),
   'setFields' => 
  array (
    'contacts' => true,
  ),
))
```

Please let me know if you need more information.

**Comment by phpfui** [comment]
This should now be working. Let me know if you find an issue.  Will get to the other issues tomorrow. Close this issue if it all works.

Thanks!

**Comment by xpavp03** [comment]
good news: `email_address` is now an object.
However, `contact_id` is still a string, not an object.

And judging from `\PHPFUI\ConstantContact\Definition\ContactResource::$fields` there's more. `created_at` and `updated_at` should be instances of `\PHPFUI\ConstantContact\DateTime`.

Thank you for your work, Bruce.

**Comment by xpavp03** [comment]
Thank you! I confirm this is fixed now.

Just a quick question:
Why do you prefer 
```php
$this->assertEquals("{$time}", "{$contacts->contacts[0]->created_at}");
```
to explicit casting
```php
$this->assertEquals((string) $time, (string) $contacts->contacts[0]->created_at);
```
or to comparing the whole thing
```php
$this->assertEquals($dataArray, $contacts->toArray());
```
I'm just trying to learn something :)

Feel free to close this ticket when ever you want. Thank you for your work, Bruce.

**Comment by phpfui** [comment]
Just lazy actually. I was comparing to a string, so I just converted in
line. Depends on context. Explicit cast would probably be better here.
