### ISSUE TITLE
Empty list_memberships skipped in ContactPutRequest when withdrawing contact from all lists

### ISSUE THREAD

**Issue by xpavp03** [phpfui/ConstantContact#26]
I'm trying to unsubscribe a contact from all lists by setting his `Definition\ContactPutRequest->list_memberships` to an empty array.

However, in `Definition\Base::getData()` are empty arrays skipped and the empty `list_memberships` attribute is not sent to the server.
https://github.com/phpfui/ConstantContact/blob/87dd954b6d2a68fc4e9f9d76511ef659840bce8b/src/ConstantContact/Definition/Base.php#L269

I suspect it's a bug because when I make the HTTP request manually from PhpStorm, and I include the empty array for `list_memberships`, the contact is unsubscribed.

```http
PUT https://api.cc.email/v3/contacts/d5e4dc88-9dbf-11ef-9af2-fa163e4d7501
Authorization: Bearer {{accessToken}}
Cache-Control: no-cache
Content-Type: application/json
Accept: */*
Connection: keep-alive
Accept-Encoding: gzip, deflate"

{
    "update_source": "Account",
    "first_name": "Petr",
    "last_name": "Pavel",
    "email_address": {
        "address": "xxxx@mailinator.com",
        "permission_to_send": "implicit"
    },
    "list_memberships": []
}
```

Thank you in advance for looking into it.

**Comment by phpfui** [comment]
I'll look into everything next week. Out of town for a while.

**Comment by phpfui** [comment]
This should now be fixed.

I also fixed a PHP error caused by the schema listing a default argument first.

Let me know if it does not work.

**Comment by xpavp03** [comment]
Thank you!
