### ISSUE TITLE
\PHPFUI\ConstantContact\Definition\Base::getfields() - incorrect method name case

### ISSUE THREAD

**Issue by xpavp03** [phpfui/ConstantContact#28]
Hi Bruce,
just noticed that the method is called "getfields" instead of "getFields".

https://github.com/phpfui/ConstantContact/blob/7c695161f06a4504c9b0601151064356e6828e2c/src/ConstantContact/Definition/Base.php#L304

**Comment by phpfui** [comment]
Thanks, can't believe it lasted that long. Released.
