### ISSUE TITLE
POST method doesn't send any body

### ISSUE THREAD

**Issue by xpavp03** [phpfui/ConstantContact#29]
Hi Bruce,
I suspect that when you refactored the `post()` method to use GuzzleFactory, you accidentally removed the `$config` with `$json`.

https://github.com/phpfui/ConstantContact/blob/557de6a51d02aec5ce8cbb9c161bd9b10d3adadf/src/ConstantContact/Client.php#L290

history:
```php
			$json = \json_encode($parameters['body'], JSON_PRETTY_PRINT);
			$guzzle = new \GuzzleHttp\Client(['headers' => $this->getHeaders(),
				'handler' => $this->guzzleHandler,
				'body' => $json, ]);
			$response = $guzzle->request('POST', $url);
```

current version:
```php
			$json = \json_encode($parameters['body'], JSON_PRETTY_PRINT);
			$response = $this->getGuzzleClient()->request('POST', $url);
```

compared to `put()` method
```php
			$json = \json_encode($parameters['body'], JSON_PRETTY_PRINT);
			$guzzle = $this->getGuzzleClient(
				$json,
				[
					'Connection' => 'keep-alive',
					'Content-Length' => \strlen($json),
					'Accept-Encoding' => 'gzip, deflate',
					'Host' => $this->host,
					'Accept' => '*/*'
				]
			);
			$response = $guzzle->request($method, $url);
```

Perhaps you even meant to remove the `post()` method's guts and call `put($url, $parameters, $method = 'POST')`.

I found out because Constant Contact complains 
```
[{"error_key":"contacts.api.validation.error","error_message":"create_source is missing, create_source does not have a valid value"}]
```
when I'm trying to add a contact. The parameter create_resource is in `$json`
```json
{
  "create_source" : "Contact",
  "first_name" : "John",
  "last_name" : "Doe",
  "list_memberships" : [ "4315271a-92f6-11ef-8029-fa163ecd39be" ],
  "email_address" : {
    "address" : "new-address@mailinator.com",
    "permission_to_send" : "explicit"
  }
}
```
and the JSON is accepted without complains (and contact is created) when I send the request from PhpStorm directly.

That got me investigating the code of `post()`.

**Comment by phpfui** [comment]
Yes, forgot to pass the json body to the factory.  Now fixed.  Let me know if this works and I will create a release.

I had to submit PR's to two other packages since they have depreciations under PHP 8.4, which I am now running. Such is life on the cutting edge. Hopefully the maintainers will merge, but I have my doubts.

**Comment by xpavp03** [comment]
Thank you for your speedy reaction. It's working now.

Looking at `post()` though, I notice that it doesn't send the same headers as `put()`. Also, the similarity of these two methods is striking, and you can even define which http method should be actually used with `put()`. So I'm curious, why didn't you write:

```php
	public function post(string $url, array $parameters) : ?array
		{
		return $this->put($url, $parameters, 'POST');
		}
```
You did the same with `patch()`.

It would be even cleaner to extract the functionality of `put()` to some private method e.g. `request()` and call `$this->request($url, $parameters, 'PUT');`

**Comment by phpfui** [comment]
Yes. Was noticing that too. But apparently I thought they were different
enough to be separate. Maybe one did not require length?
