### ISSUE TITLE
Request for PHP 7.4 support.

### ISSUE THREAD

**Issue by hidroforix** [phpfui/ConstantContact#4]
Constant Contact requires us to upgrade the API to V3 before Aug/2022. Currently, our system is using PHP7.4, we can not wait for upgrading the PHP version from 7.4 to 8.0, Thus could you please create a version that supports PHP7.4???

**Comment by phpfui** [comment]
The code was written for 8.0 and I have no interest in back porting it.

I would suggest you clone the repo and then run [Rector](https://packagist.org/packages/rector/rector) on it.  You should be able to just run this [downgrade](https://github.com/rectorphp/rector/blob/HEAD//docs/rector_rules_overview.md#downgradephp74) on it.  Let me know if that does not work.

Once you port to PHP 8.0, you can stop using the downgraded library and use the 8.0 port.  I plan to support 8.0 at least until 8.3 comes out.

Hope this helps.

**Comment by phpfui** [comment]
Closing this as PHP 7.4 is no longer supported by PHP
