### ISSUE TITLE
Token vars blank after calling RefreshToken

### ISSUE THREAD

**Issue by degive** [phpfui/ConstantContact#5]
I set the $client->accessToken & client->$refreshToken vars then do a refreshTocken() and the $client->accessToken & $client->refreshToken are blank after that?

Any Idea why?

**Comment by phpfui** [comment]
Can you post your code?

Initial setup is complex. Make sure you have sessions enabled. Follow all instructions in readme.

**Comment by degive** [comment]
I did follow the readme and have session on, here is the code. Thank you for your help!

session_start();
include("ConstantContact/vendor/autoload.php");

//Constant Contact v3
$apiKey="..................";
$secret="............";
$url="https://rpat.org/includes/cc_api_auth.php";

// Create a client
$client = new \PHPFUI\ConstantContact\Client($apiKey, $secret, $url);

//First Time Save Tokens
$auth=XSS2("auth");
if ($auth!="")
{
	header('location: ' . $client->getAuthorizationURL());
	exit();
}

// Set access and refresh tokens on client
$sql="SELECT * FROM cc_auth WHERE id=1";
$result = MySqliQuery($sql);
if ($rs = MySqliFetchArray($result))
{
	$client->accessToken = $rs["code"];
	$client->refreshToken = $rs["state"];
	echo "Cur Auth: ".$client->accessToken." | ".$client->refreshToken."<br>";
}

// Refresh the tokens.  
$res=$client->refreshToken();
echo $res."<br>";
echo "New Auth: ".$client->accessToken." | ".$client->refreshToken."<br>";

Here is the output of the run:
Cur Auth: b5_P2V0uYtiu9fVlw7qsGTYJuk9oOO1m7hFWmzcUEuU | 246713f845f5c945
New Auth: |

**Comment by degive** [comment]
Thank you. This works!

**Comment by phpfui** [comment]
Awesome!
